name: Push on Epitech repository

on:
  push:
    branches:
      - develop     
jobs: 
  build:
    if: github.repository == 'PlockGames/plock_backend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.AUTOMNE_TOKEN }}

      - name: Clone Epitech repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'EpitechMscProPromo2025'
          repository: 'T-ESP-800-project_esp800-56365-TLS-tiktok_game'
          branch: 'develop'
          access-token: ${{ secrets.AUTOMNE_TOKEN }}
    
      - name: Copy code from commit to the cloned repo and git push 
        run: |
          ls -la .
          rm -rf T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/
          mkdir -p T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/
          rm  .github/workflows/mirror*
          rm  -rf .git
          ls -la T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/
          sudo rsync -a .*  T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/ --exclude='.' --exclude='..' --exclude='T-ESP-800-project_esp800-56365-TLS-tiktok_game'
          sudo rsync -a * T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/ --exclude='T-ESP-800-project_esp800-56365-TLS-tiktok_game'
          if [ -d "T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/plock_backend" ]; then rm -rf T-ESP-800-project_esp800-56365-TLS-tiktok_game/back/plock_backend; fi

      - name: Commit files
        run: |
          cd T-ESP-800-project_esp800-56365-TLS-tiktok_game/back
          git config --local user.email "$GITHUB_ACTOR_EMAIL"
          git config --local user.name "$GITHUB_ACTOR"
          echo "$GITHUB_ACTOR_EMAIL"
          git add *
          git add .*
          git commit -m "${{ github.ref  }}"
          git push --force
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_ACTOR: ${{ github.actor}}
          GITHUB_ACTOR_EMAIL: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          
